name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Zip build files
        run: |
          zip simple-line-marker-${GITHUB_REF_NAME}.zip main.js manifest.json styles.css

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF_NAME}"

          gh release create "$tag" \
            --title="Simple Line Marker $tag" \
            --draft \
            main.js manifest.json styles.css simple-line-marker-$tag.zip
